(()=>{const supabase=window.supabaseClient;if(!supabase)return;const $=id=>document.getElementById(id);
function message(text,type="info"){const el=$("message");if(!el)return;el.textContent=text||"";el.className=text?`form-message ${type}`:"";el.style.cssText=text?"margin:12px 0;padding:10px 12px;border-radius:8px;border:1px solid #d0d7de;":"";}
function busy(form,on,text){const b=form?.querySelector('button[type="submit"]');if(!b)return;if(on){b.dataset.originalText=b.textContent;b.disabled=true;b.textContent=text||"Please wait…";}else{b.disabled=false;b.textContent=b.dataset.originalText||b.textContent;}}
async function login(form){const email=$("email")?.value.trim(),password=$("password")?.value,role=$("role")?.value;if(!email||!password||!role){message("Enter your email, password and portal.","error");return;}busy(form,true,"Signing in…");try{const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;const actual=await getAuthenticatedRole(data.user);if(actual!==role){await supabase.auth.signOut();throw new Error(actual?`This account belongs to the ${AUTH_ROLE_LABELS[actual]} portal.`:"No portal profile is linked to this account yet.");}location.href=getRoleRoute(actual);}catch(e){console.error(e);message(e.message||"Unable to sign in.","error");}finally{busy(form,false);}}
async function signup(form){const name=$("name")?.value.trim(),email=$("email")?.value.trim(),password=$("password")?.value,confirm=$("confirmPassword")?.value,role=$("role")?.value,terms=$("terms");if(!name||!email||!password||!confirm||!role){message("Complete all required fields.","error");return;}if(password.length<6){message("Password must contain at least 6 characters.","error");return;}if(password!==confirm){message("Passwords do not match.","error");return;}if(terms&&!terms.checked){message("Please accept the platform terms.","error");return;}if(role==="admin"){message("Government/Admin accounts must be provisioned by an administrator.","error");return;}busy(form,true,"Creating account…");try{const {data,error}=await supabase.auth.signUp({email,password,options:{data:{full_name:name,role}}});if(error)throw error;if(data.session){message("Account created. Continue to your profile.","success");location.href=getRoleRoute(role);return;}message("Account created. Check your email to confirm your account, then sign in.","success");form.reset();}catch(e){console.error(e);message(e.message||"Unable to create the account.","error");}finally{busy(form,false);}}
async function forgot(form){const email=$("email")?.value.trim();if(!email){message("Enter your registered email address.","error");return;}busy(form,true,"Sending…");try{const redirectTo=new URL("reset.html",location.href).href;const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo});if(error)throw error;message("If an account exists for that email, a password-reset link has been sent.","success");}catch(e){console.error(e);message(e.message||"Unable to start password recovery.","error");}finally{busy(form,false);}}
async function reset(form){const password=$("password")?.value,confirm=$("confirmPassword")?.value;if(!password||password.length<6){message("New password must contain at least 6 characters.","error");return;}if(password!==confirm){message("Passwords do not match.","error");return;}busy(form,true,"Updating…");try{const {error}=await supabase.auth.updateUser({password});if(error)throw error;message("Password updated successfully. You can now sign in.","success");setTimeout(()=>location.href="index.html",900);}catch(e){console.error(e);message(e.message||"Unable to update the password.","error");}finally{busy(form,false);}}
async function logout(){await supabase.auth.signOut();location.href="index.html";}
document.addEventListener("DOMContentLoaded",()=>{document.querySelectorAll(".show-btn[data-target]").forEach(b=>b.addEventListener("click",()=>{const i=$(b.dataset.target);if(!i)return;const show=i.type!=="text";i.type=show?"text":"password";b.textContent=show?"Hide":"Show";}));const f1=$("loginForm");if(f1)f1.addEventListener("submit",e=>{e.preventDefault();login(f1)});const f2=$("signupForm");if(f2)f2.addEventListener("submit",e=>{e.preventDefault();signup(f2)});const f3=$("forgotForm");if(f3)f3.addEventListener("submit",e=>{e.preventDefault();forgot(f3)});const f4=$("resetForm");if(f4)f4.addEventListener("submit",e=>{e.preventDefault();reset(f4)});document.querySelectorAll("[data-auth-logout]").forEach(b=>b.addEventListener("click",logout));});})();
