/* Rozgaar Mitra — Person 2 static build
   Plain HTML + CSS + JavaScript. No React, Vite, Tailwind or JSX.
*/
(() => {
  const sb = window.supabaseClient;
  const DEMO = false;
  const app = document.getElementById('app');
  const state = {
    user: null, provider: null, courses: [], batches: [], trainees: [], enrollments: [],
    view: 'dashboard', params: {}, mobile: false, loading: false, error: '', notice: '',
    demo: DEMO, charts: []
  };

  const SECTORS = ['Electronics & Hardware','Healthcare','Retail','Construction','IT-ITeS','Apparel & Textile','Automotive','Food Processing'];
  const LEVELS = ['NSQF Level 3','NSQF Level 4','NSQF Level 5','NSQF Level 6'];
  const DROPOUT_REASONS = ['Personal / family','Financial','Migration','Attendance','Skill gap','No suitable job','Salary expectations','Location','Qualification mismatch','Lack of experience','Other'];

  const demoSeed = () => {
    const p = {id:'demo-provider',userId:'demo-user',organizationName:'Maharashtra Skills Training Centre',providerType:'Training Provider',email:'provider@example.com',phone:'+91 98765 43210',address:'Pune, Maharashtra',district:'Pune',city:'Pune',verificationStatus:'Verified'};
    const c1={id:'demo-c1',providerId:p.id,name:'Web Development',description:'Frontend and full-stack web development programme.',sector:'IT-ITeS',durationHours:240,level:'NSQF Level 4',certificationAvailable:true,status:'Active'};
    const c2={id:'demo-c2',providerId:p.id,name:'Healthcare Assistant',description:'Foundational patient care and clinical support skills.',sector:'Healthcare',durationHours:180,level:'NSQF Level 3',certificationAvailable:true,status:'Active'};
    const b1={id:'demo-b1',courseId:c1.id,name:'WD-PUNE-06',startDate:'2026-08-01',endDate:'2026-11-15',location:'Pune Centre',capacity:30,status:'Ongoing'};
    const b2={id:'demo-b2',courseId:c2.id,name:'HCA-PUNE-04',startDate:'2026-09-10',endDate:'2026-12-20',location:'Pune Centre',capacity:25,status:'Upcoming'};
    const ts=[
      {id:'demo-t1',name:'Aarav Patil',phone:'+91 90000 00001',district:'Pune',status:'Ongoing',attendancePct:82,progressPct:68,batchId:b1.id,enrollmentId:'demo-e1',enrollmentStatus:'Active',enrollmentDate:'2026-08-01',dropoutReason:'',dropoutNotes:''},
      {id:'demo-t2',name:'Meera Shinde',phone:'+91 90000 00002',district:'Satara',status:'Ongoing',attendancePct:61,progressPct:44,batchId:b1.id,enrollmentId:'demo-e2',enrollmentStatus:'Active',enrollmentDate:'2026-08-03',dropoutReason:'',dropoutNotes:''},
      {id:'demo-t3',name:'Rohan Jadhav',phone:'+91 90000 00003',district:'Pune',status:'Completed',attendancePct:91,progressPct:100,batchId:b1.id,enrollmentId:'demo-e3',enrollmentStatus:'Completed',enrollmentDate:'2026-08-02',dropoutReason:'',dropoutNotes:''},
      {id:'demo-t4',name:'Sana Khan',phone:'+91 90000 00004',district:'Nashik',status:'Dropped Out',attendancePct:39,progressPct:22,batchId:b1.id,enrollmentId:'demo-e4',enrollmentStatus:'Dropped',enrollmentDate:'2026-08-05',dropoutReason:'Migration',dropoutNotes:'Moved to another district for family reasons.'}
    ];
    return {provider:p,courses:[c1,c2],batches:[b1,b2],trainees:ts,enrollments:[]};
  };

  function setDemoData() {
    const saved = localStorage.getItem('sih26135_person2_demo');
    const d = saved ? JSON.parse(saved) : demoSeed();
    Object.assign(state,d); state.user={id:'demo-user',email:state.provider.email};
    saveDemo();
  }
  function saveDemo(){ if(DEMO) localStorage.setItem('sih26135_person2_demo', JSON.stringify({provider:state.provider,courses:state.courses,batches:state.batches,trainees:state.trainees,enrollments:state.enrollments})); }
  function uid(){ return crypto.randomUUID ? crypto.randomUUID() : 'id-'+Date.now()+'-'+Math.random().toString(16).slice(2); }
  function esc(v){ return String(v ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); }
  function fmtDate(v){ return v ? new Date(v+'T00:00:00').toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}) : '—'; }
  function badge(status){ const cls={Active:'active',Ongoing:'ongoing',Completed:'completed','Dropped Out':'dropped',Archived:'archived'}[status]||'neutral'; return `<span class="badge badge-${cls}">${esc(status||'—')}</span>`; }
  function button(text, cls='btn-primary', attrs=''){ return `<button class="btn ${cls}" ${attrs}>${text}</button>`; }
  function pageHead(title, subtitle, action=''){ return `<div class="page-head"><div><h1>${esc(title)}</h1><p>${esc(subtitle)}</p></div>${action}</div>`; }
  function card(content, cls=''){ return `<div class="card ${cls}">${content}</div>`; }
  function stat(label,value,sub='',tone='pine'){ return `<div class="card stat"><div class="stat-label">${esc(label)}</div><div class="stat-value ${tone}">${esc(value)}</div>${sub?`<div class="stat-sub">${esc(sub)}</div>`:''}</div>`; }
  function empty(title,body){ return `<div class="empty"><h3>${esc(title)}</h3><p>${esc(body)}</p></div>`; }
  function field(label, input){ return `<div class="form-field"><label>${esc(label)}</label>${input}</div>`; }
  function input(name,value='',type='text',extra=''){ return `<input class="input" id="${esc(name)}" name="${esc(name)}" type="${type}" value="${esc(value)}" ${extra}>`; }
  function select(name,value,options,extra=''){ return `<select class="select" id="${esc(name)}" name="${esc(name)}" ${extra}>${options.map(o=>`<option value="${esc(o)}" ${o===value?'selected':''}>${esc(o)}</option>`).join('')}</select>`; }
  function textArea(name,value='',extra=''){ return `<textarea class="textarea" id="${esc(name)}" name="${esc(name)}" rows="3" ${extra}>${esc(value)}</textarea>`; }

  async function getSession(){
    const session = await window.SIHAuth.getSession();
    state.user = session?.user || null;
  }
  async function loadData(){
    if(DEMO) return;
    if(!state.user){ state.provider=null; state.courses=[]; state.batches=[]; state.trainees=[]; return; }
    state.loading=true; render();
    try{
      let {data:p,error}=await sb.from('training_providers').select('*').eq('user_id',state.user.id).maybeSingle();
      if(error) throw error;
      if(!p){
        const name=state.user.user_metadata?.organization_name||state.user.user_metadata?.full_name||state.user.email?.split('@')[0]||'Training Provider';
        const {data:created,error:ce}=await sb.from('training_providers').insert({user_id:state.user.id,organization_name:name,provider_type:'Training Provider',email:state.user.email||null}).select('*').single();
        if(ce) throw ce; p=created;
      }
      state.provider=mapProvider(p);
      const [cr,br,er]=await Promise.all([
        sb.from('courses').select('*').eq('provider_id',state.provider.id).order('created_at',{ascending:false}),
        sb.from('batches').select('*').order('created_at',{ascending:false}),
        sb.from('enrollments').select('id,trainee_id,batch_id,enrollment_date,status,created_at').order('created_at',{ascending:false})
      ]);
      if(cr.error) throw cr.error; if(br.error) throw br.error; if(er.error) throw er.error;
      state.courses=(cr.data||[]).map(mapCourse);
      const ownCourseIds=new Set(state.courses.map(c=>c.id));
      state.batches=(br.data||[]).map(mapBatch).filter(b=>ownCourseIds.has(b.courseId));
      const ownBatchIds=new Set(state.batches.map(b=>b.id));
      state.enrollments=(er.data||[]).map(mapEnrollment).filter(e=>ownBatchIds.has(e.batchId));
      const ids=[...new Set(state.enrollments.map(e=>e.traineeId).filter(Boolean))];
      let rows=[];
      if(ids.length){ const tr=await sb.from('trainees').select('*').in('id',ids); if(tr.error) throw tr.error; rows=tr.data||[]; }
      const first=new Map(); state.enrollments.forEach(e=>{if(!first.has(e.traineeId)) first.set(e.traineeId,e)});
      state.trainees=rows.map(r=>mapTrainee(r,first.get(r.id)));
    }catch(e){ state.error=e.message||'Unable to load provider data.'; }
    finally{state.loading=false; render();}
  }
  const mapProvider=r=>({id:r.id,userId:r.user_id,organizationName:r.organization_name||'',providerType:r.provider_type||'',email:r.email||'',phone:r.phone||'',address:r.address||'',district:r.district||'',city:r.city||'',verificationStatus:r.verification_status||'Pending'});
  const mapCourse=r=>({id:r.id,providerId:r.provider_id,name:r.course_name,description:r.description||'',sector:r.sector||'',durationHours:r.duration_hours??'',level:r.level||'',certificationAvailable:Boolean(r.certification_available),status:r.status||'Active'});
  const mapBatch=r=>({id:r.id,courseId:r.course_id,name:r.batch_name,startDate:r.start_date||'',endDate:r.end_date||'',location:r.location||'',capacity:Number(r.capacity??0),status:r.status||'Upcoming'});
  const mapEnrollment=r=>({id:r.id,traineeId:r.trainee_id,batchId:r.batch_id,enrollmentDate:r.enrollment_date||r.created_at||null,status:r.status||'Active'});
  const mapTrainee=(r,e)=>({id:r.id,userId:r.user_id,batchId:e?.batchId||null,enrollmentId:e?.id||null,enrollmentStatus:e?.status||null,enrollmentDate:e?.enrollmentDate||null,name:r.name,phone:r.phone||'',district:r.district||'',status:r.status||'Ongoing',attendancePct:Number(r.attendance_pct??0),progressPct:Number(r.progress_pct??0),dropoutReason:r.dropout_reason||'',dropoutNotes:r.dropout_notes||''});

  async function refresh(){ state.error=''; state.notice=''; if(DEMO){saveDemo();render();return;} await loadData(); }
  async function call(action){ try{state.error='';await action();state.notice='Saved successfully.';await refresh();}catch(e){state.error=e.message||'Operation failed.';render();} }

  async function signIn(){ window.SIHAuth.redirectToLogin(); }
  async function signUp(){ window.SIHAuth.redirectToLogin(); }
  async function signOut(){ await window.SIHAuth.signOut(); window.SIHAuth.redirectToLogin(); }

  function nav(key,params={}){state.view=key;state.params=params;document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===key));renderMain();}
  function openModal(title,body){ document.getElementById('modal-root').innerHTML=`<div class="modal-backdrop" id="modal-bg"><div class="modal"><div class="modal-head"><h2>${esc(title)}</h2><button class="icon-btn" data-action="close-modal" aria-label="Close">×</button></div><div class="modal-body">${body}</div></div></div>`; }
  function closeModal(){document.getElementById('modal-root').innerHTML='';}

  function renderAuth(){
    window.SIHAuth.redirectToLogin();
  }

  function shell(){
    const navItems=[['dashboard','⌂','Dashboard'],['profile','▣','Provider profile'],['courses','▤','Courses'],['batches','▥','Batches'],['trainees','♙','Trainees'],['attendance','✓','Attendance'],['dropouts','!','Dropouts'],['analytics','◒','Analytics'],['assessments','☷','Assessments'],['certifications','★','Certifications'],['outcomes','↗','Outcomes']];
    app.innerHTML=`<div class="layout"><aside class="sidebar" id="sidebar"><div class="side-head"><div class="side-brand">Rozgaar Mitra</div><div class="side-sub">Training Provider Portal</div></div><nav class="nav">${navItems.map(([k,i,l])=>`<button data-view="${k}" class="${state.view===k?'active':''}"><span class="nav-icon">${i}</span>${l}</button>`).join('')}</nav><div class="side-foot"><div class="side-org">${esc(state.provider?.organizationName||state.user?.email||'Training Provider')}</div><button class="btn btn-ghost full" style="color:#fff;border-color:rgba(255,255,255,.22)" data-action="signout">↪ Sign out</button></div></aside><div class="main"><div class="mobile-head"><button data-action="open-menu">☰</button><strong>Rozgaar Mitra</strong><span></span></div><main class="content" id="main-content"></main></div></div><div id="modal-root"></div>`;
    document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;state.params={};closeMobile();renderMain();});
    document.querySelector('[data-action="signout"]').onclick=()=>call(signOut);
    document.querySelector('[data-action="open-menu"]').onclick=()=>document.getElementById('sidebar').classList.add('open');
    renderMain();
  }
  function closeMobile(){document.getElementById('sidebar')?.classList.remove('open');}
  function render(){ if(!state.user){renderAuth();return;} if(!state.provider&&!DEMO){app.innerHTML='<div class="loading">Loading provider workspace…</div>';return;} shell(); }

  function renderMain(){
    const el=document.getElementById('main-content'); if(!el)return;
    if(state.error){ /* page-level error is displayed below */ }
    let html='';
    switch(state.view){case'dashboard':html=dashboard();break;case'profile':html=profile();break;case'courses':html=courses();break;case'batches':html=batches();break;case'trainees':html=trainees();break;case'attendance':html=attendance();break;case'dropouts':html=dropouts();break;case'analytics':html=analytics();break;case'assessments':html=integration('Assessments','Skill assessments use the shared trainee skill model. This portal intentionally does not create a duplicate assessments table.','☷');break;case'certifications':html=integration('Certifications','Certification availability is stored on the shared course record. No duplicate certifications table is created.','★');break;case'outcomes':html=integration('Employment outcomes','Placement, follow-ups, employment history, skill gaps and outcome analytics belong to the shared Person 4 outcome model.','↗');break;default:html=dashboard();}
    el.innerHTML=(state.error?`<div class="notice error">${esc(state.error)}</div>`:'')+(state.notice?`<div class="notice success">${esc(state.notice)}</div>`:'')+html;
    bindMain();
  }
  function dashboard(){
    const ongoing=state.trainees.filter(t=>t.status==='Ongoing').length,completed=state.trainees.filter(t=>t.status==='Completed').length,dropped=state.trainees.filter(t=>t.status==='Dropped Out').length,atRisk=state.trainees.filter(t=>t.status==='Ongoing'&&t.attendancePct<75).length;
    const activeB=state.batches.filter(b=>b.status==='Ongoing'); const risk=[...state.trainees.filter(t=>t.status==='Ongoing'&&t.attendancePct<75),...state.trainees.filter(t=>t.status==='Dropped Out')].slice(0,7);
    return pageHead('Dashboard',"A live view of the provider's courses, batches, trainee roster and early-risk signals.")+`<div class="grid grid-4" style="margin-bottom:22px">${stat('Trainees ongoing',ongoing,'','ochre')}${stat('Completed training',completed,'','pine')}${stat('Dropped out',dropped,`${state.trainees.length?Math.round(dropped/state.trainees.length*100):0}% of roster`,'brick')}${stat('Attendance risk',atRisk,'< 75% attendance','moss')}</div><div class="grid grid-3"><div class="card card-pad span-2"><div class="section-row"><h3 class="section-title">Batches in progress</h3><button class="link-btn" data-nav="batches">View all →</button></div>${activeB.length?activeB.map(b=>{const c=state.courses.find(c=>c.id===b.courseId),n=state.trainees.filter(t=>t.batchId===b.id).length;return `<div class="risk-item"><div style="display:flex;justify-content:space-between"><div><strong>${esc(b.name)}</strong><div class="small muted">${esc(c?.name||'Course')} · ${esc(b.location||'Location not set')}</div></div><div class="right"><strong>${n}/${b.capacity}</strong><div class="small muted">enrolled</div></div></div></div>`}).join(''):'<p class="muted small">No batches currently running.</p>'}</div><div class="card card-pad"><div class="section-row"><h3 class="section-title">Risk & dropout flags</h3><span class="ochre">!</span></div><div class="risk-list">${risk.length?risk.map(t=>`<div class="risk-item"><div style="display:flex;justify-content:space-between;gap:10px"><span>${esc(t.name)}</span>${badge(t.status==='Ongoing'?`${t.attendancePct}%`:'Dropped')}</div><div class="small muted">${esc(t.status==='Dropped Out'?(t.dropoutReason||'Reason not recorded'):'Attendance below 75%')}</div></div>`).join(''):'<p class="muted small">No current risk or dropout flags.</p>'}</div></div></div>`;
  }

  function profile(){const p=state.provider||{};return pageHead('Provider profile','The authenticated training provider record used to scope courses and batches.',button('Edit profile','btn-ghost','data-action="edit-profile"'))+`<div class="grid grid-3"><div class="card card-pad span-2"><div style="display:flex;align-items:center;gap:13px"><div style="width:48px;height:48px;border-radius:7px;background:var(--pine);color:#fff;display:grid;place-items:center;font-size:22px">▣</div><div><h2 class="section-title" style="font-size:20px">${esc(p.organizationName||'Unnamed provider')}</h2><div class="small muted">${esc(p.providerType||'Training Provider')}</div></div></div><div class="divider"></div><div class="info-grid">${info('Provider record ID',p.id||'—',true)}${info('Verification',p.verificationStatus||'Pending')}${info('District',p.district||'—')}${info('City',p.city||'—')}${info('Contact number',p.phone||'—')}${info('Account email',p.email||state.user?.email||'—')}${info('Registered address',p.address||'—')}</div></div><div class="card card-pad"><div class="label" style="margin-bottom:12px">Courses offered</div>${state.courses.filter(c=>c.status==='Active').length?state.courses.filter(c=>c.status==='Active').map(c=>`<div class="risk-item"><div style="display:flex;justify-content:space-between;gap:10px"><span>${esc(c.name)}</span><span class="small muted">${esc(c.level||'—')}</span></div></div>`).join(''):'<p class="muted small">No active courses yet.</p>'}</div></div>`;}
  function info(label,value,mono=false){return `<div><div class="info-label">${esc(label)}</div><div class="info-value ${mono?'small':''}">${esc(value)}</div></div>`;}

  function courses(){const archived=state.params.archived||false;const list=state.courses.filter(c=>archived?c.status==='Archived':c.status!=='Archived');return pageHead('Courses','Define the programmes your organization delivers using the shared training catalogue.',button('＋ New course','btn-primary','data-action="new-course"'))+`<div class="tabs"><button class="tab ${!archived?'active':''}" data-course-tab="active">Active</button><button class="tab ${archived?'active':''}" data-course-tab="archived">Archived</button></div>${list.length?`<div class="table-wrap"><table><thead><tr><th>Course</th><th>Sector</th><th>Duration</th><th>Level</th><th>Certificate</th><th>Status</th><th></th></tr></thead><tbody>${list.map(c=>`<tr><td><strong>${esc(c.name)}</strong><div class="small muted">${esc(c.description||'No description')}</div></td><td>${esc(c.sector||'—')}</td><td>${c.durationHours?esc(c.durationHours)+' h':'—'}</td><td>${esc(c.level||'—')}</td><td>${c.certificationAvailable?'Yes':'No'}</td><td>${badge(c.status)}</td><td class="right"><button class="link-btn" data-edit-course="${c.id}">Edit</button> <button class="link-btn" data-toggle-course="${c.id}">${c.status==='Archived'?'Restore':'Archive'}</button></td></tr>`).join('')}</tbody></table></div>`:empty('No courses here yet','Create a course to start building batches.')}`;}
  function batches(){return pageHead('Batches','Schedule course runs with dates, delivery location, capacity and enrollment counts.',button('＋ New batch','btn-primary','data-action="new-batch"'))+(state.batches.length?`<div class="table-wrap"><table><thead><tr><th>Batch</th><th>Course</th><th>Location</th><th>Dates</th><th>Enrolled</th><th>Status</th><th></th></tr></thead><tbody>${state.batches.map(b=>{const c=state.courses.find(c=>c.id===b.courseId),n=state.trainees.filter(t=>t.batchId===b.id).length;return `<tr><td><strong>${esc(b.name)}</strong></td><td>${esc(c?.name||'—')}</td><td>${esc(b.location||'—')}</td><td class="small">${esc(b.startDate||'—')} → ${esc(b.endDate||'—')}</td><td><button class="link-btn" data-nav-trainees="${b.id}">♙ ${n}/${b.capacity}</button></td><td>${badge(b.status)}</td><td class="right"><button class="link-btn" data-edit-batch="${b.id}">Edit</button></td></tr>`}).join('')}</tbody></table></div>`:empty('No batches yet',state.courses.length?'Create a batch for one of your courses.':'Create a course first, then add a batch.'));}

  function trainees(){const bf=state.params.batchId||'all';const sf=state.params.status||'all';const list=state.trainees.filter(t=>(bf==='all'||t.batchId===bf)&&(sf==='all'||t.status===sf));return pageHead('Trainees','Provider roster from shared trainee records. This portal manages batch enrollment and provider-side progress fields.',button('＋ Assign trainee','btn-primary','data-action="assign-trainee"'))+`<div class="toolbar">${select('batch-filter',bf,['all',...state.batches.map(b=>b.id)],'data-filter="batch"').replaceAll('<option value="all">all</option>','<option value="all">All batches</option>')}${select('status-filter',sf,['all','Ongoing','Completed','Dropped Out'],'data-filter="status"').replace('<option value="all">all</option>','<option value="all">All statuses</option>')}</div>${list.length?`<div class="table-wrap"><table><thead><tr><th>Trainee</th><th>Batch</th><th>District</th><th>Attendance</th><th>Progress</th><th>Status</th><th></th></tr></thead><tbody>${list.map(t=>{const b=state.batches.find(b=>b.id===t.batchId);return `<tr><td><strong>${esc(t.name)}</strong></td><td>${esc(b?.name||'—')}</td><td>${esc(t.district||'—')}</td><td>${t.attendancePct}%</td><td><div class="progress"><div style="width:${Math.max(0,Math.min(100,t.progressPct))}%"></div></div></td><td>${badge(t.status)}</td><td class="right"><button class="link-btn" data-view-trainee="${t.id}">View</button></td></tr>`}).join('')}</tbody></table></div>`:empty('No enrolled trainees','Use Assign trainee with a trainee UUID from the shared trainee record.')}`;}
  function attendance(){const bf=state.params.batchId||'all';const list=state.trainees.filter(t=>t.status!=='Dropped Out'&&(bf==='all'||t.batchId===bf));return pageHead('Attendance','Maintain the running attendance percentage used for early dropout-risk detection.')+`<div class="toolbar">${select('attendance-batch',bf,['all',...state.batches.map(b=>b.id)],'data-attendance-filter').replace('<option value="all">all</option>','<option value="all">All batches</option>')}</div>${list.length?`<div class="table-wrap"><table><thead><tr><th>Trainee</th><th>Batch</th><th>Attendance</th><th>Risk</th><th>Adjust</th></tr></thead><tbody>${list.map(t=>{const b=state.batches.find(b=>b.id===t.batchId);const risk=t.attendancePct<50?'High risk':t.attendancePct<75?'Watch':'Healthy';return `<tr><td><strong>${esc(t.name)}</strong></td><td>${esc(b?.name||'—')}</td><td>${badge(t.attendancePct>=75?'Active':t.attendancePct>=50?'Ongoing':'Dropped')} ${t.attendancePct}%</td><td>${risk}</td><td class="right"><button class="link-btn" data-att="${t.id}" data-delta="-5">−5</button> <button class="link-btn" data-att="${t.id}" data-delta="5">+5</button></td></tr>`}).join('')}</tbody></table></div>`:empty('No active trainees','Enroll trainees into a provider batch to start tracking attendance.')}`;}
  function dropouts(){const dropped=state.trainees.filter(t=>t.status==='Dropped Out');const filtered=state.params.reason&&state.params.reason!=='all'?dropped.filter(t=>t.dropoutReason===state.params.reason):dropped;const counts=DROPOUT_REASONS.map(r=>({r,n:dropped.filter(t=>t.dropoutReason===r).length})).filter(x=>x.n);const notPlaced=state.trainees.filter(t=>t.status==='Completed'&&t.outcome&&!t.outcome.placed);return pageHead('Dropouts & non-placement','Why trainees left training, or completed without finding suitable work — grouped by reason.')+`<div class="grid grid-3" style="margin-bottom:22px"><div class="card card-pad span-2"><h3 class="section-title">Dropout reasons</h3><div style="margin-top:15px">${counts.length?counts.map(c=>`<div class="bar-row"><button class="link-btn" style="text-align:left" data-reason="${esc(c.r)}">${esc(c.r)}</button><div class="bar-track"><div class="bar-fill" style="width:${Math.round(c.n/dropped.length*100)}%"></div></div><span class="small">${c.n}</span></div>`).join(''):'<p class="muted small">No dropouts recorded.</p>'}</div></div><div class="card card-pad"><h3 class="section-title">Completed, not placed</h3><p class="muted small">Trainees who finished training but have not found suitable work.</p><div class="stat-value ochre" style="font-size:30px">${notPlaced.length}</div>${notPlaced.slice(0,3).map(t=>`<div class="risk-item small">${esc(t.name)}</div>`).join('')}</div></div>${filtered.length?`<div class="table-wrap"><table><thead><tr><th>Trainee</th><th>Batch</th><th>Reason</th><th>Notes</th></tr></thead><tbody>${filtered.map(t=>`<tr><td><strong>${esc(t.name)}</strong></td><td>${esc(state.batches.find(b=>b.id===t.batchId)?.name||'—')}</td><td>${badge('Dropped Out')} ${esc(t.dropoutReason||'—')}</td><td class="small muted">${esc(t.dropoutNotes||'—')}</td></tr>`).join('')}</tbody></table></div>`:empty('No records','No dropouts match this filter.')}`;}

  function analytics(){const total=state.trainees.length,completed=state.trainees.filter(t=>t.status==='Completed').length,dropped=state.trainees.filter(t=>t.status==='Dropped Out').length,ongoing=state.trainees.filter(t=>t.status==='Ongoing').length;const avgA=total?Math.round(state.trainees.reduce((s,t)=>s+t.attendancePct,0)/total):0,avgP=total?Math.round(state.trainees.reduce((s,t)=>s+t.progressPct,0)/total):0;return pageHead('Analytics','Provider-level training performance derived from the shared course, batch and trainee records.')+`<div class="grid grid-4" style="margin-bottom:18px">${stat('Completion rate',`${total?Math.round(completed/total*100):0}%`,'','pine')}${stat('Dropout rate',`${total?Math.round(dropped/total*100):0}%`,'','brick')}${stat('Avg. attendance',`${avgA}%`,'','ochre')}${stat('Avg. progress',`${avgP}%`,'','moss')}</div><div class="grid grid-4" style="margin-bottom:22px">${stat('Total trainees',total,'','ochre')}${stat('Active courses',state.courses.filter(c=>c.status==='Active').length,'','pine')}${stat('Running batches',state.batches.filter(b=>b.status==='Ongoing').length,'','moss')}${stat('At-risk trainees',state.trainees.filter(t=>t.status==='Ongoing'&&t.attendancePct<75).length,'','brick')}</div><div class="grid grid-3"><div class="card card-pad span-2"><h3 class="section-title">Course performance — enrolled vs completed</h3><div class="chart-box"><canvas id="course-chart"></canvas></div></div><div class="card card-pad"><h3 class="section-title">Trainee status split</h3><div class="chart-box"><canvas id="status-chart"></canvas></div><div class="small muted">Ongoing: ${ongoing} · Completed: ${completed} · Dropped: ${dropped}</div></div></div>`;}
  function integration(title,body,icon){return pageHead(title,'Shared-data integration boundary.')+card(`<div style="width:44px;height:44px;border-radius:7px;background:rgba(30,72,68,.1);color:var(--pine);display:grid;place-items:center;font-size:21px;margin-bottom:14px">${icon}</div><h2 class="section-title" style="font-size:20px">${esc(title==='Assessments'?'Use the shared skill model':title==='Certifications'?'No duplicate certification table':'Use the shared outcome source of truth')}</h2><p class="muted small" style="line-height:1.7;max-width:650px">${esc(body)}</p>`,'card-pad');}

  function courseModal(id){const c=id?state.courses.find(x=>x.id===id):{name:'',sector:SECTORS[0],description:'',durationHours:240,level:LEVELS[0],certificationAvailable:true};openModal(id?'Edit course':'New course',`<form id="course-form"><div class="form-grid">${field('Course name',input('c-name',c.name,'text','required autofocus'))}${field('Sector',select('c-sector',c.sector,SECTORS))}${field('Duration (hours)',input('c-duration',c.durationHours,'number','min="1" required'))}${field('NSQF level',select('c-level',c.level,LEVELS))}${field('Description',textArea('c-description',c.description),'')}${field('Certification',select('c-cert',c.certificationAvailable?'yes':'no',['yes','no']))}</div><div class="actions">${button('Cancel','btn-ghost','data-action="close-modal" type="button"')}${button('Save course','btn-primary','type="submit"')}</div></form>`);document.getElementById('course-form').onsubmit=e=>{e.preventDefault();const v={name:val('c-name'),sector:val('c-sector'),description:val('c-description'),durationHours:Number(val('c-duration')),level:val('c-level'),certificationAvailable:val('c-cert')==='yes'};call(async()=>{if(DEMO){if(id)Object.assign(state.courses.find(x=>x.id===id),v);else state.courses.unshift({id:uid(),providerId:state.provider.id,...v,status:'Active'});saveDemo();closeModal();return;}const row={...(id?{}:{provider_id:state.provider.id}),course_name:v.name.trim(),description:v.description.trim()||null,sector:v.sector||null,duration_hours:v.durationHours,level:v.level||null,certification_available:v.certificationAvailable};const q=id?sb.from('courses').update(row).eq('id',id):sb.from('courses').insert(row);const r=await q;if(r.error)throw r.error;closeModal();});};}
  function batchModal(id){const b=id?state.batches.find(x=>x.id===id):{courseId:state.courses[0]?.id||'',name:'',startDate:'',endDate:'',location:'',capacity:30,status:'Upcoming'};openModal(id?'Edit batch':'New batch',`<form id="batch-form"><div class="form-grid">${field('Course',select('b-course',b.courseId,state.courses.map(c=>c.id)))}${field('Batch name',input('b-name',b.name,'text','required'))}${field('Start date',input('b-start',b.startDate,'date'))}${field('End date',input('b-end',b.endDate,'date'))}${field('Training location',input('b-location',b.location))}${field('Capacity',input('b-capacity',b.capacity,'number','min="1" required'))}${field('Status',select('b-status',b.status,['Upcoming','Ongoing','Completed']))}</div><div class="actions">${button('Cancel','btn-ghost','data-action="close-modal" type="button"')}${button('Save batch','btn-primary','type="submit"')}</div></form>`);document.getElementById('batch-form').onsubmit=e=>{e.preventDefault();const v={courseId:val('b-course'),name:val('b-name'),startDate:val('b-start'),endDate:val('b-end'),location:val('b-location'),capacity:Number(val('b-capacity')),status:val('b-status')};call(async()=>{if(DEMO){if(id)Object.assign(state.batches.find(x=>x.id===id),v);else state.batches.unshift({id:uid(),...v});saveDemo();closeModal();return;}const row={course_id:v.courseId,batch_name:v.name.trim(),start_date:v.startDate||null,end_date:v.endDate||null,location:v.location.trim()||null,capacity:v.capacity,status:v.status};const q=id?sb.from('batches').update(row).eq('id',id):sb.from('batches').insert(row);const r=await q;if(r.error)throw r.error;closeModal();});};}
  function assignModal(){openModal('Assign existing trainee to batch',`<p class="small muted">Trainee identity data belongs to the shared trainee module. Enter the trainee UUID and choose the provider batch.</p><form id="assign-form">${field('Trainee UUID',input('a-trainee','','text','required placeholder="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"'))}${field('Batch',select('a-batch','',state.batches.map(b=>b.id)))}<div class="actions">${button('Cancel','btn-ghost','data-action="close-modal" type="button"')}${button('Assign','btn-primary','type="submit"')}</div></form>`);document.getElementById('assign-form').onsubmit=e=>{e.preventDefault();const tid=val('a-trainee').trim(),bid=val('a-batch');call(async()=>{if(DEMO){const t=state.trainees.find(x=>x.id===tid)||null;if(!t){throw new Error('In demo mode, use one of the existing demo trainee IDs.');}t.batchId=bid;t.enrollmentStatus='Active';t.enrollmentDate=new Date().toISOString();saveDemo();closeModal();return;}const r=await sb.from('enrollments').insert({trainee_id:tid,batch_id:bid});if(r.error)throw r.error;closeModal();});};}
  function profileModal(){const p=state.provider||{};openModal('Edit provider profile',`<form id="profile-form"><div class="form-grid">${field('Organization name',input('p-org',p.organizationName,'text','required'))}${field('Provider type',input('p-type',p.providerType))}${field('District',input('p-district',p.district))}${field('City',input('p-city',p.city))}${field('Phone',input('p-phone',p.phone))}${field('Email',input('p-email',p.email,'email'))}${field('Registered address',textArea('p-address',p.address))}</div><div class="actions">${button('Cancel','btn-ghost','data-action="close-modal" type="button"')}${button('Save changes','btn-primary','type="submit"')}</div></form>`);document.getElementById('profile-form').onsubmit=e=>{e.preventDefault();const v={organization_name:val('p-org').trim(),provider_type:val('p-type').trim()||'Training Provider',district:val('p-district').trim()||null,city:val('p-city').trim()||null,phone:val('p-phone').trim()||null,email:val('p-email').trim()||null,address:val('p-address').trim()||null};call(async()=>{if(DEMO){Object.assign(state.provider,{organizationName:v.organization_name,providerType:v.provider_type,district:v.district||'',city:v.city||'',phone:v.phone||'',email:v.email||'',address:v.address||''});saveDemo();closeModal();return;}const r=await sb.from('training_providers').update(v).eq('id',state.provider.id);if(r.error)throw r.error;closeModal();});};}
  function val(id){return document.getElementById(id)?.value||'';}

  function traineeDrawer(id){const t=state.trainees.find(x=>x.id===id);if(!t)return;const b=state.batches.find(x=>x.id===t.batchId);openModal(t.name,`<div class="small muted">${esc(t.id)}</div><div class="metrics"><div><div class="metric-label">Attendance</div><div class="metric-value">${t.attendancePct}%</div></div><div><div class="metric-label">Progress</div><div class="metric-value">${t.progressPct}%</div></div></div><div class="info-grid">${info('Phone',t.phone||'—')}${info('District',t.district||'—')}${info('Batch',b?.name||'—')}${info('Enrollment',t.enrollmentStatus||'—')}${info('Enrolled on',fmtDate(t.enrollmentDate))}${info('Status',t.status)}</div>${t.status==='Dropped Out'?`<div class="divider"></div><div class="info-label brick">Dropout reason</div><div>${esc(t.dropoutReason||'Not recorded')}</div><p class="small muted">${esc(t.dropoutNotes||'')}</p>`:''}<div class="actions"><button class="btn btn-ghost" data-action="copy-trainee" data-id="${esc(t.id)}">Copy UUID</button><button class="btn btn-primary" data-action="close-modal">Close</button></div>`);}

  function bindMain(){
    document.querySelectorAll('[data-nav]').forEach(x=>x.onclick=()=>nav(x.dataset.nav));
    document.querySelectorAll('[data-nav-trainees]').forEach(x=>x.onclick=()=>nav('trainees',{batchId:x.dataset.navTrainees}));
    document.querySelectorAll('[data-action="edit-profile"]').forEach(x=>x.onclick=profileModal);
    document.querySelectorAll('[data-action="new-course"]').forEach(x=>x.onclick=()=>courseModal());
    document.querySelectorAll('[data-edit-course]').forEach(x=>x.onclick=()=>courseModal(x.dataset.editCourse));
    document.querySelectorAll('[data-toggle-course]').forEach(x=>x.onclick=()=>call(async()=>{const c=state.courses.find(c=>c.id===x.dataset.toggleCourse);const next=c.status==='Archived'?'Active':'Archived';if(DEMO){c.status=next;saveDemo();return;}const r=await sb.from('courses').update({status:next}).eq('id',c.id);if(r.error)throw r.error;}));
    document.querySelectorAll('[data-course-tab]').forEach(x=>x.onclick=()=>nav('courses',{archived:x.dataset.courseTab==='archived'}));
    document.querySelectorAll('[data-action="new-batch"]').forEach(x=>x.onclick=()=>state.courses.length?batchModal():null);
    document.querySelectorAll('[data-edit-batch]').forEach(x=>x.onclick=()=>batchModal(x.dataset.editBatch));
    document.querySelectorAll('[data-action="assign-trainee"]').forEach(x=>x.onclick=assignModal);
    document.querySelectorAll('[data-view-trainee]').forEach(x=>x.onclick=()=>traineeDrawer(x.dataset.viewTrainee));
    document.querySelectorAll('[data-filter]').forEach(x=>x.onchange=()=>{state.params={...state.params,[x.dataset.filter==='batch'?'batchId':'status']:x.value};renderMain();});
    document.querySelectorAll('[data-attendance-filter]').forEach(x=>x.onchange=()=>{state.params.batchId=x.value;renderMain();});
    document.querySelectorAll('[data-att]').forEach(x=>x.onclick=()=>call(async()=>{const t=state.trainees.find(t=>t.id===x.dataset.att);const next=Math.max(0,Math.min(100,t.attendancePct+Number(x.dataset.delta)));if(DEMO){t.attendancePct=next;saveDemo();return;}const r=await sb.from('trainees').update({attendance_pct:next}).eq('id',t.id);if(r.error)throw r.error;}));
    document.querySelectorAll('[data-reason]').forEach(x=>x.onclick=()=>{state.params.reason=state.params.reason===x.dataset.reason?'all':x.dataset.reason;renderMain();});
    document.querySelectorAll('[data-action="close-modal"]').forEach(x=>x.onclick=closeModal);
    document.querySelectorAll('[data-action="copy-trainee"]').forEach(x=>x.onclick=async()=>{try{await navigator.clipboard.writeText(x.dataset.id);state.notice='Trainee UUID copied.';closeModal();renderMain();}catch{state.notice='UUID: '+x.dataset.id;closeModal();renderMain();}});
    if(state.view==='analytics') drawCharts();
  }
  function drawCharts(){state.charts.forEach(c=>c.destroy());state.charts=[];const cc=document.getElementById('course-chart'),sc=document.getElementById('status-chart');if(!window.Chart||!cc||!sc)return;const labels=state.courses.filter(c=>c.status!=='Archived').map(c=>c.name.length>18?c.name.slice(0,16)+'…':c.name);const enrolled=state.courses.filter(c=>c.status!=='Archived').map(c=>{const ids=state.batches.filter(b=>b.courseId===c.id).map(b=>b.id);return state.trainees.filter(t=>ids.includes(t.batchId)).length});const comp=state.courses.filter(c=>c.status!=='Archived').map(c=>{const ids=state.batches.filter(b=>b.courseId===c.id).map(b=>b.id);return state.trainees.filter(t=>ids.includes(t.batchId)&&t.status==='Completed').length});state.charts.push(new Chart(cc,{type:'bar',data:{labels,datasets:[{label:'Enrolled',data:enrolled},{label:'Completed',data:comp}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom'}},scales:{y:{beginAtZero:true,ticks:{precision:0}}}}}));const s=['Ongoing','Completed','Dropped Out'];state.charts.push(new Chart(sc,{type:'doughnut',data:{labels:s,datasets:[{data:s.map(x=>state.trainees.filter(t=>t.status===x).length)}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom'}}}}));}

  // Global modal event delegation + auth/session bootstrap.
  document.addEventListener('click',e=>{if(e.target.id==='modal-bg')closeModal();});
  (async()=>{try{await getSession();if(!DEMO){sb.auth.onAuthStateChange((_event,session)=>{state.user=session?.user||null;if(state.user)loadData();else render();});}if(state.user)await loadData();render();}catch(e){state.error=e.message||'Startup error';render();}})();
})();
